//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Spanform.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_SPANFOTYPE                  129
#define IDD_ANAL                        130
#define IDD_PROG                        131
#define IDD_INFO                        132
#define IDB_TITLE                       133
#define IDD_DISPLAY                     134
#define IDC_Rectangular                 1005
#define IDC_Hamming                     1006
#define IDC_slide50                     1011
#define IDC_slide700                    1012
#define IDC_slide200                    1013
#define IDC_slide400                    1014
#define IDC_slide500                    1015
#define IDC_slide600                    1016
#define IDC_slide300                    1017
#define IDC_slide150                    1018
#define IDC_slide100                    1019
#define IDC_PROGRESS1                   1022
#define IDC_12000Cut                    1030
#define IDC_9000cut                     1031
#define IDC_6000cut                     1032
#define IDC_nocut                       1033
#define IDC_Keep                        1036
#define IDC_AnalysisCancel              1037
#define IDC_infoname                    1039
#define IDC_infosamprate                1040
#define IDC_infobits                    1041
#define IDC_infolength                  1042
#define IDC_infochannels                1043
#define IDC_infosampunits               1044
#define IDC_infoanalframes              1045
#define IDC_infoframesize               1046
#define IDC_infopower2                  1047
#define IDC_infoslide                   1048
#define IDC_infowindow                  1049
#define IDC_infocutoff                  1050
#define IDC_unitleft                    1051
#define IDC_unitsanalyzed               1052
#define IDC_Expo                        1053
#define IDC_Linear                      1054
#define IDC_Hz                          1055
#define IDC_Letters                     1056
#define IDC_COLOR                       1057
#define IDC_BW                          1058
#define IDC_hor                         1060
#define IDC_vert                        1061
#define IDC_Sensitive                   1062
#define IDC_noize                       1063
#define IDC_size128                     1067
#define IDC_size256                     1068
#define IDC_size512                     1069
#define IDC_size1024                    1070
#define IDC_size2048                    1071
#define IDC_size4096                    1072
#define ID_FILE_CREATE                  32771
#define ID_SPANFORM_SHOWFILEINFO        32773
#define ID_SPANFORM_SENSITIVITY         32774
#define ID_SPANFORM_NOISETHRESHOLD      32775
#define ID_SPANFORM_ADJUSTSIZE_BIGGER   32776
#define ID_SPANFORM_ADJUSTSIZE_SMALLER  32777
#define ID_SPANFORM_ADJUSTSIZE_ORIGINALSIZE 32778
#define ID_SPANFORM_ADJUSTSIZE_INCREASEHORIZONTAL 32779
#define ID_SPANFORM_ADJUSTSIZE_DECREASEHORIZONTAL 32780
#define ID_SPANFORM_DISPLAY_COLOR       32781
#define ID_SPANFORM_DISPLAY_GRAYS       32782
#define ID_SPANFORM_DISPLAY             32789
#define ID_AUDIO_PLAY                   32790
#define ID_AUDIO_STOP                   32791
#define ID_AUDIO_ASSOCIATE              32793
#define ID_AUDIO_RESTART                32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
